using System.Net.Http.Json;
using System.Net.WebSockets;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Drawing.Drawing2D;

ApplicationConfiguration.Initialize();
Application.Run(new MainForm());

sealed class Pin { public string pinId {get;set;}=""; public string clientId {get;set;}=""; public string name {get;set;}=""; public string color {get;set;}="red"; public double x {get;set;} public double y {get;set;} public int? number {get;set;} }
sealed class RoomState { public int? mapId {get;set;} public string mapName {get;set;}="Waiting for ToN log…"; public string roundType {get;set;}=""; public Dictionary<string,Pin> pins {get;set;}=new(); }

sealed class MainForm : Form {
 const string Server="https://ton-pin-system.onrender.com";
 static readonly Regex RoundRx=new(@"This round is taking place at (.*?) \((\d+)\) and the round type is (.+?)\s*$",RegexOptions.Compiled);
 static readonly Regex JoinRx=new(@"\[Behaviour\] Joining (wrld_[^\s]+)",RegexOptions.Compiled);
 readonly HttpClient http=new(){Timeout=TimeSpan.FromSeconds(8)}; readonly CancellationTokenSource stop=new();
 readonly MapPanel map=new(){Dock=DockStyle.Fill,BackColor=Color.FromArgb(18,18,20)}; readonly Label title=new(){AutoSize=true,ForeColor=Color.White,Font=new Font("Segoe UI",13,FontStyle.Bold)}; readonly Label status=new(){AutoSize=true,ForeColor=Color.Silver};
 readonly TextBox nameBox=new(){Width=130,PlaceholderText="表示名"}; readonly ComboBox colorBox=new(){Width=105,DropDownStyle=ComboBoxStyle.DropDownList}; readonly TrackBar sizeBar=new(){Minimum=14,Maximum=48,Value=26,TickStyle=TickStyle.None,Width=110};
 readonly Button deleteBtn=new(){Text="自分のピン削除",AutoSize=true}; RoomState state=new(); string? room; string clientId; string currentLog=""; string? lastRoundKey;
 readonly Dictionary<int,string> names=new(){[0]="Warehouse",[1]="Sewers",[2]="Construct",[3]="Neon Towers (Purple)",[4]="Innyume",[5]="Secret",[6]="Backrooms",[7]="The Fishbowl",[8]="Forest",[9]="Experimentation",[10]="Playplace",[11]="Sanctum",[12]="Sea Base",[13]="Astral",[14]="Pizzeria",[15]="Isolation",[16]="Hell",[17]="Schoolhouse",[18]="Ancient",[19]="Throne",[20]="Neon Towers (Green)",[21]="Car Park",[22]="Blackspace",[23]="Museum",[24]="Inner Tower",[25]="Pools",[26]="TBH",[27]="Development",[28]="Hotel",[29]="Elevator",[30]="Hole",[31]="Iteration_0",[32]="Scrapyard",[33]="Robland",[34]="Baseplate",[35]="Challenge Cube",[36]="Have",[37]="Gardens",[38]="Dust",[39]="Dots",[40]="Engine",[41]="Orange",[42]="The Wall",[43]="Nexus",[44]="Space Colony",[45]="Altar",[46]="Desktop",[47]="SlashCo HQ",[48]="Harvest",[49]="Heaven",[50]="Hightower",[51]="Lounge",[52]="Mall",[53]="Skyscraper",[54]="Nightlife",[55]="Snowfield",[56]="Gaol",[57]="Mineshaft",[58]="Chess",[59]="Cheese Maze",[60]="Wafflehouse",[61]="Tunnels",[62]="Subway",[63]="Supply Route",[64]="Vents",[65]="Escape Route",[66]="Garten",[67]="Black Forest",[68]="This Map Does Not Exist",[69]="Luna Hills",[70]="Park",[71]="Hub",[72]="Spaceless"};
 public MainForm(){Text="ToN Pin System";MinimumSize=new Size(760,520);Size=new Size(1100,720);BackColor=Color.FromArgb(24,24,27);ForeColor=Color.White;StartPosition=FormStartPosition.CenterScreen;clientId=LoadSetting("clientId")??Guid.NewGuid().ToString("N");SaveSetting("clientId",clientId);nameBox.Text=LoadSetting("name")??"";colorBox.Items.AddRange(["チェイス (赤)","生存希望 (緑)","その他 (青)"]);colorBox.SelectedIndex=0;
  var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=76,Padding=new Padding(12,8,12,4),BackColor=Color.FromArgb(31,31,35),WrapContents=false};top.Controls.Add(title);top.Controls.Add(new Label{Text="   名前",AutoSize=true,ForeColor=Color.Silver,Padding=new Padding(0,5,0,0)});top.Controls.Add(nameBox);top.Controls.Add(colorBox);top.Controls.Add(new Label{Text="ピンサイズ",AutoSize=true,ForeColor=Color.Silver,Padding=new Padding(8,5,0,0)});top.Controls.Add(sizeBar);top.Controls.Add(deleteBtn);top.Controls.Add(status);Controls.Add(map);Controls.Add(top);
  map.PinSize=sizeBar.Value;map.PinClicked=PlacePin;sizeBar.ValueChanged+=(s,e)=>{map.PinSize=sizeBar.Value;map.Invalidate();};nameBox.TextChanged+=(s,e)=>SaveSetting("name",nameBox.Text.Trim());deleteBtn.Click+=async(s,e)=>await RemoveMine();FormClosing+=(s,e)=>stop.Cancel();Shown+=(s,e)=>_=WatchLoop(); }
 string AppDir=>Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"ToNPinSystem"); string Settings=>Path.Combine(AppDir,"settings.json");
 string? LoadSetting(string key){try{var d=JsonSerializer.Deserialize<Dictionary<string,string>>(File.ReadAllText(Settings));return d!=null&&d.TryGetValue(key,out var v)?v:null;}catch{return null;}}
 void SaveSetting(string key,string value){try{Directory.CreateDirectory(AppDir);Dictionary<string,string> d;try{d=JsonSerializer.Deserialize<Dictionary<string,string>>(File.ReadAllText(Settings))??new();}catch{d=new();}d[key]=value;File.WriteAllText(Settings,JsonSerializer.Serialize(d));}catch{}}
 string RoomKey(string loc)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes("ton-pin-v1|"+loc))).ToLowerInvariant()[..40];
 async Task JoinRoom(string r){if(room==r&&_active?.State==WebSocketState.Open)return;room=r;status.Text=" 接続中…";try{if(_active?.State==WebSocketState.Open)await _active.CloseAsync(WebSocketCloseStatus.NormalClosure,"switch",CancellationToken.None);}catch{};var sock=new ClientWebSocket();
  await ConnectSocket(sock,r); }
 async Task ConnectSocket(ClientWebSocket sock,string r){try{var uri=new Uri(Server.Replace("https://","wss://").Replace("http://","ws://")+"/native");await sock.ConnectAsync(uri,stop.Token);_active=sock;await Send(new{type="join",room=r});status.Text=" 同期接続済み";_ = ReceiveLoop(sock);}catch(Exception ex){status.Text=" 接続失敗: "+ex.Message;}}
 ClientWebSocket? _active;
 async Task Send(object obj){var s=_active;if(s?.State!=WebSocketState.Open)return;var b=Encoding.UTF8.GetBytes(JsonSerializer.Serialize(obj));await s.SendAsync(b,WebSocketMessageType.Text,true,stop.Token);}
 async Task ReceiveLoop(ClientWebSocket sock){var buf=new byte[65536];try{while(sock.State==WebSocketState.Open&&!stop.IsCancellationRequested){using var ms=new MemoryStream();WebSocketReceiveResult rr;do{rr=await sock.ReceiveAsync(buf,stop.Token);if(rr.MessageType==WebSocketMessageType.Close)return;ms.Write(buf,0,rr.Count);}while(!rr.EndOfMessage);using var doc=JsonDocument.Parse(ms.ToArray());if(doc.RootElement.GetProperty("type").GetString()=="state"){var st=doc.RootElement.GetProperty("state").Deserialize<RoomState>();if(st!=null)BeginInvoke(()=>ApplyState(st));}}}catch{if(!stop.IsCancellationRequested)BeginInvoke(()=>status.Text=" 同期切断（ログ更新時に再接続）");}}
 void ApplyState(RoomState st){var changed=state.mapId!=st.mapId;state=st;title.Text=st.mapId is null?st.mapName:$"{st.mapName} · {st.mapId}   {st.roundType}";map.State=st;if(changed)map.LoadMap(st.mapId);map.Invalidate();}
 async void PlacePin(double x,double y){if(room==null||state.mapId==null||string.IsNullOrWhiteSpace(nameBox.Text))return;var c=colorBox.SelectedIndex switch{1=>"green",2=>"blue",_=>"red"};await Send(new{type="setPin",clientId,name=nameBox.Text.Trim(),color=c,x,y,mapId=state.mapId});}
 async Task RemoveMine(){var p=state.pins.Values.FirstOrDefault(p=>p.clientId==clientId);if(p!=null)await Send(new{type="removePin",pinId=p.pinId,clientId});}
 string? LatestLog(){var dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"AppData","LocalLow","VRChat","VRChat");if(!Directory.Exists(dir))return null;return Directory.GetFiles(dir,"output_log_*.txt").OrderByDescending(File.GetLastWriteTimeUtc).FirstOrDefault();}
 async Task WatchLoop(){while(!stop.IsCancellationRequested){try{var p=LatestLog();if(p==null){status.Text=" VRChatログ待機中";await Task.Delay(1500,stop.Token);continue;}if(p!=currentLog){currentLog=p;await ScanExisting(p);}await TailOnce(p);await Task.Delay(180,stop.Token);}catch(OperationCanceledException){}catch(Exception ex){status.Text=" ログ監視: "+ex.Message;await Task.Delay(1500);}}}
 async Task ScanExisting(string p){var lines=File.ReadLines(p).TakeLast(10000);string? loc=null;Match? round=null;foreach(var line in lines){var j=JoinRx.Match(line);if(j.Success)loc=j.Groups[1].Value;var m=RoundRx.Match(line);if(m.Success)round=m;}if(loc!=null){await JoinRoom(RoomKey(loc));if(round!=null)await PostRound(round);}_tailPos=new FileInfo(p).Length;}
 long _tailPos;
 async Task TailOnce(string p){using var fs=new FileStream(p,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete);if(_tailPos>fs.Length)_tailPos=0;fs.Position=_tailPos;using var sr=new StreamReader(fs,Encoding.UTF8,true,4096,true);string? line;while((line=await sr.ReadLineAsync())!=null){var j=JoinRx.Match(line);if(j.Success)await JoinRoom(RoomKey(j.Groups[1].Value));var m=RoundRx.Match(line);if(m.Success)await PostRound(m);}_tailPos=fs.Position;}
 async Task PostRound(Match m){if(room==null)return;var id=int.Parse(m.Groups[2].Value);var key=$"{id}|{m.Groups[3].Value}";if(key==lastRoundKey)return;lastRoundKey=key;var payload=new{mapId=id,mapName=names.GetValueOrDefault(id,m.Groups[1].Value),roundType=m.Groups[3].Value};try{await http.PostAsJsonAsync($"{Server}/api/room/{room}/round",payload,stop.Token);}catch(Exception ex){status.Text=" ラウンド送信失敗: "+ex.Message;}}
}

sealed class MapPanel:Panel{
 public RoomState State=new(); public int PinSize=26; public Action<double,double>? PinClicked; Image? image;
 public MapPanel(){DoubleBuffered=true;Cursor=Cursors.Cross;MouseClick+=(s,e)=>{if(e.Button!=MouseButtons.Left||image==null)return;var r=ImageRect();if(!r.Contains(e.Location))return;PinClicked?.Invoke((e.X-r.X)/r.Width,(e.Y-r.Y)/r.Height);};}
 public void LoadMap(int? id){image?.Dispose();image=null;if(id==null)return;var dir=Path.Combine(AppContext.BaseDirectory,"data","Maps");
  if(!Directory.Exists(dir))dir=Path.Combine(AppContext.BaseDirectory,"Maps");
  foreach(var ext in new[]{"png","jpg","jpeg","webp"}){var p=Path.Combine(dir,$"{id}.{ext}");if(File.Exists(p)){try{image=Image.FromFile(p);break;}catch{}}}}
 RectangleF ImageRect(){if(image==null)return RectangleF.Empty;float s=Math.Min(ClientSize.Width/(float)image.Width,ClientSize.Height/(float)image.Height);var w=image.Width*s;var h=image.Height*s;return new((ClientSize.Width-w)/2,(ClientSize.Height-h)/2,w,h);}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;if(image==null){using var b=new SolidBrush(Color.Gray);e.Graphics.DrawString("マップ待機中",new Font("Segoe UI",16),b,20,20);return;}var r=ImageRect();e.Graphics.DrawImage(image,r);foreach(var p in State.pins.Values){float x=r.X+(float)p.x*r.Width,y=r.Y+(float)p.y*r.Height,s=PinSize;var c=p.color switch{"green"=>Color.FromArgb(45,200,100),"blue"=>Color.FromArgb(70,145,255),_=>Color.FromArgb(235,70,70)};using var b=new SolidBrush(c);using var pen=new Pen(Color.FromArgb(220,255,255,255),2);e.Graphics.FillEllipse(b,x-s/2,y-s/2,s,s);e.Graphics.DrawEllipse(pen,x-s/2,y-s/2,s,s);if(p.color=="red"&&p.number is int n){var f=new Font("Segoe UI",Math.Max(8,s*.38f),FontStyle.Bold);var t=n.ToString();var z=e.Graphics.MeasureString(t,f);e.Graphics.DrawString(t,f,Brushes.White,x-z.Width/2,y-z.Height/2);}using var lf=new Font("Segoe UI",Math.Max(8,s*.32f),FontStyle.Bold);var ls=e.Graphics.MeasureString(p.name,lf);using var bg=new SolidBrush(Color.FromArgb(150,0,0,0));e.Graphics.FillRectangle(bg,x-ls.Width/2-3,y-s/2-ls.Height-5,ls.Width+6,ls.Height+2);e.Graphics.DrawString(p.name,lf,Brushes.White,x-ls.Width/2,y-s/2-ls.Height-4);}}
}
